# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u5458\u5de5', 'verbose_name_plural': '\u5458\u5de5'},
        ),
    ]
