# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170724_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u7ba1\u7406\u5458', 'verbose_name_plural': '\u7ba1\u7406\u5458'},
        ),
    ]
