# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u90e8\u95e8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u540d\u79f0',
                'verbose_name_plural': '\u90e8\u95e8\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('\u6240\u5c5e\u90e8\u95e8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Department')),
            ],
            options={
                'verbose_name': '\u804c\u4f4d\u540d\u79f0',
                'verbose_name_plural': '\u804c\u4f4d\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6, verbose_name='\u6027\u522b')),
                ('identity_card', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='\u8eab\u4efd\u8bc1')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Position', verbose_name='\u6240\u5c5e\u804c\u4f4d')),
            ],
            options={
                'verbose_name': '\u804c\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u804c\u5458\u4fe1\u606f',
            },
        ),
    ]
