# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u90e8\u95e8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8\u540d\u79f0',
                'verbose_name_plural': '\u90e8\u95e8\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u804c\u4f4d\u540d\u79f0')),
                ('\u6240\u5c5e\u90e8\u95e8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
