# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170709_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='\u6240\u5c5e\u90e8\u95e8',
        ),
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Department', verbose_name='\u6240\u5c5e\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1'),
        ),
    ]
