# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170724_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '\u90e8\u95e8', 'verbose_name_plural': '\u90e8\u95e8'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '\u804c\u5458', 'verbose_name_plural': '\u804c\u5458'},
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u804c\u4f4d'),
        ),
    ]
