# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20170724_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='identity_type',
            field=models.SmallIntegerField(choices=[(1, '\u8eab\u4efd\u8bc1'), (2, '\u5c45\u6c11\u8bc1')], default=1, verbose_name='\u8bc1\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.SmallIntegerField(choices=[(1, '\u672c\u79d1'), (2, '\u7814\u7a76\u751f'), (3, '\u535a\u58eb')], default=1, verbose_name='\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '\u7537'), (2, '\u5973')], default=1, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='identity_card',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='\u8bc1\u4ef6\u53f7'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='political_status',
            field=models.SmallIntegerField(choices=[(1, '\u7fa4\u4f17'), (2, '\u56e2\u5458'), (3, '\u9884\u5907\u515a\u5458'), (4, '\u515a\u5458')], default=1, verbose_name='\u653f\u6cbb\u9762\u8c8c'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ\u53f7'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.SmallIntegerField(choices=[(1, '\u5728\u804c'), (2, '\u79bb\u804c'), (3, '\u5b9e\u4e60')], default=1, verbose_name='\u804c\u5458\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.SmallIntegerField(choices=[(1, '\u5168\u804c'), (2, '\u517c\u804c')], default=1, verbose_name='\u804c\u5458\u7c7b\u578b'),
        ),
    ]
