# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20170724_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birth_type',
            field=models.SmallIntegerField(choices=[(1, '\u516c\u5386'), (2, '\u519c\u5386')], default=1, verbose_name='\u751f\u65e5\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='staff',
            name='birthday',
            field=models.DateField(null=True, verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='staff',
            name='birthplace',
            field=models.CharField(max_length=10, null=True, verbose_name='\u7c4d\u8d2f'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_man',
            field=models.CharField(max_length=10, null=True, verbose_name='\u7d27\u6025\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contact_mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='\u7d27\u6025\u8054\u7cfb\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='staff',
            name='e_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='\u5de5\u4f5c\u90ae\u7bb1'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_master',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u90e8\u95e8\u7ba1\u7406\u8005'),
        ),
        migrations.AddField(
            model_name='staff',
            name='marriage',
            field=models.SmallIntegerField(choices=[(1, '\u672a\u5a5a'), (2, '\u5df2\u5a5a'), (3, '\u5df2\u5a5a\u5df2\u80b2')], default=1, verbose_name='\u5a5a\u59fb\u72b6\u51b5'),
        ),
        migrations.AddField(
            model_name='staff',
            name='people',
            field=models.CharField(default='\u6c49\u65cf', max_length=11, verbose_name='\u6c11\u65cf'),
        ),
        migrations.AddField(
            model_name='staff',
            name='wxid',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u5fae\u4fe1'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.SmallIntegerField(choices=[(1, '\u672c\u79d1'), (2, '\u7814\u7a76\u751f'), (3, '\u535a\u58eb')], default=1, verbose_name='\u6700\u9ad8\u5b66\u5386'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='\u4e2a\u4eba\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='identity_type',
            field=models.SmallIntegerField(choices=[(1, '\u8eab\u4efd\u8bc1'), (2, '\u62a4\u7167')], default=1, verbose_name='\u8bc1\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.Position', verbose_name='\u804c\u4f4d'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qq',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_status',
            field=models.SmallIntegerField(choices=[(1, '\u5728\u804c'), (2, '\u79bb\u804c'), (3, '\u5b9e\u4e60')], default=1, verbose_name='\u5458\u5de5\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.SmallIntegerField(choices=[(1, '\u5168\u804c'), (2, '\u517c\u804c')], default=1, verbose_name='\u5458\u5de5\u7c7b\u578b'),
        ),
    ]
